' GNSS Navigation Data Provider service architecture

@startuml

!include ../../lib/theme.iuml!2

rectangle "Cloud service 1" {
    component [FTP server] as cs1.ftp
}

rectangle "Cloud service 2" {
    component [FTP server] as cs2.ftp
}

rectangle "My microservice" {

    rectangle "Docker container" as dc1 <<nested>> {
      component [Cache] as my.cache
    }

    rectangle "Docker container" as dc2 <<nested>> {
      component [API] as my.api
    }

    Interface "TCP" as apicache
    my.cache -- apicache
    apicache -- my.api
    
}

rectangle "Client device" {
    component [HTTP Client] as cli.app
}

Interface "FTP" as cs1api
cs1.ftp -- cs1api
cs1api -- my.api

Interface "FTP" as cs2api
cs2.ftp -- cs2api
cs2api -- my.api

Interface "HTTP/Rest" as apicli
my.api -- apicli
apicli -- cli.app

@enduml
